export default {
  radius: '3px',
  spacing: {
    margin: '8px',
    padding: {
      default: '10px',
      top: '10px',
      bottom: '10px',
      left: '15px',
      right: '15px',
      topBottom: '10px',
      leftRight: '15px',
    },
    iconSize: 24,
    borderSize: 1,
    shadowSize: 1,
  },
  font: {
    size: 16,
    weight: 200,
    lineHeight: 18,
    family: 'Roboto, sans-serif',
  },
  h1: {
    size: 32,
    weight: 900,
    lineHeight: 64,
  },
  h2: {
    size: 24,
    weight: 700,
    lineHeight: 32,
  },
  h3: {
    size: 18,
    weight: 500,
    lineHeight: 24,
  },
  selected: {
    size: 0,
    weight: 10,
    lineHeight: 0,
  },
  hover: {
    size: 0,
    weight: 10,
    lineHeight: 0,
  },
  transitions: {
    in: undefined,
    out: undefined,
  },
  palette: {
    default: '#fff',
    defaultText: 'white',
    defaultDisabled: undefined,
    defaultHover: '#eee',
    defaultSelected: undefined,
    defaultBorder: '#C0C0C0',
    primary: '#000000',
    primaryText: '#fff',
    primaryDisabled: undefined,
    primaryHover: 'undefined',
    primarySelected: undefined,
    primaryBorder: undefined,
    secondary: 'blue',
    secondaryText: 'red',
    secondaryDisabled: undefined,
    secondaryHover: undefined,
    secondarySelected: undefined,
    secondaryBorder: undefined,
    disabled: 'lightgray',
    shadow: 'black',
  },
};
