export default {
  radius: '3px',
  spacing: {
    margin: '8px',
    padding: {
      default: '10px',
      top: '10px',
      bottom: '10px',
      left: '15px',
      right: '15px',
      topBottom: '10px',
      leftRight: '15px',
    },
    iconSize: 24,
    borderSize: 1,
    shadowSize: 1,
  },
  font: {
    size: 16,
    weight: 200,
    lineHeight: 18,
    family: 'Roboto, sans-serif',
  },
  h1: {
    fontSize: '28px',
    fontWeight: 600,
    lineHeight: '30px',
  },
  h2: {
    fontSize: '24px',
    fontWeight: 400,
    lineHeight: '28px',
  },
  h3: {
    fontSize: '20px',
    fontWeight: 300,
    lineHeight: '24px',
  },
  h4: {
    fontSize: '18px',
    fontWeight: 300,
    lineHeight: '20px',
  },
  h5: {
    fontSize: '14px',
    fontWeight: 300,
    lineHeight: '16px',
  },
  h6: {
    fontSize: '12px',
    fontWeight: 300,
    lineHeight: '14px',
  },
  selected: {
    size: 0,
    weight: 10,
    lineHeight: 0,
  },
  hover: {
    size: 0,
    weight: 10,
    lineHeight: 0,
  },
  transitions: {
    in: undefined,
    out: undefined,
  },
  palette: {
    default: '#fff',
    defaultText: '#4c4c4c',
    defaultDisabled: undefined,
    defaultHover: '#eee',
    defaultSelected: undefined,
    defaultBorder: '#ededed',
    primary: '#4cafa0',
    primaryText: '#fff',
    primaryDisabled: undefined,
    primaryHover: 'undefined',
    primarySelected: undefined,
    primaryBorder: undefined,
    secondary: 'blue',
    secondaryText: 'red',
    secondaryDisabled: undefined,
    secondaryHover: undefined,
    secondarySelected: undefined,
    secondaryBorder: undefined,
    disabled: 'lightgray',
    shadow: 'black',
  },
};
