export default {
  radius: '3px',
  media: {
    xs: '(min-width: 480px)',
    sm: '(min-width: 736px)',
    md: '(min-width: 980px)',
    lg: '(min-width: 1280px)',
    xl: '(min-width: 1690px)',
  },
  spacing: {
    margin: '8px',
    padding: {
      default: '8px',
      top: '8px',
      bottom: '8px',
      left: '10px',
      right: '10px',
      topBottom: '10px',
      leftRight: '15px',
    },
    borderSize: 1,
    shadowSize: 1,
  },
  dimensions: {
    icon: {
      large: '24px',
      medium: '16px',
      small: '8px',
    },
    height: {
      large: '40px',
      medium: '30px',
      small: '20px',
    },
  },
  font: {
    size: '16px',
    weight: 200,
    lineHeight: 18,
    family: 'Roboto, sans-serif',
  },
  h1: {
    fontSize: '28px',
    fontWeight: 600,
    lineHeight: '30px',
  },
  h2: {
    fontSize: '24px',
    fontWeight: 400,
    lineHeight: '28px',
  },
  h3: {
    fontSize: '20px',
    fontWeight: 300,
    lineHeight: '24px',
  },
  h4: {
    fontSize: '18px',
    fontWeight: 300,
    lineHeight: '20px',
  },
  h5: {
    fontSize: '14px',
    fontWeight: 300,
    lineHeight: '16px',
  },
  h6: {
    fontSize: '12px',
    fontWeight: 300,
    lineHeight: '14px',
  },
  transitions: {
    ease: '.25,.1,.25,1',
    linear: '0,0,1,1',
    easeIn: '.42,0,1,1',
    easeOut: '0,0,.58,1',
    easeInOut: '.42,0,.58,1',
  },
  palette: {
    default: '#ffffff',
    primary: '#1a5a99',
    secondary: '#5dcebb',
    defaultText: '#4c4c4c',
    primaryText: '#ffffff',
    secondaryText: '#195382',
    defaultDisabled: '#ededed',
    primaryDisabled: '#9ebbd7',
    secondaryDisabled: '#9ad1ec',
    defaultTextDisabled: '#cecece',
    primaryTextDisabled: '#c6d8e7',
    secondaryTextDisabled: '#cae5f4',
    defaultHover: '#f5f7f7',
    primaryHover: '#164872',
    secondaryHover: '#217bad',
    defaultSelected: '#ededed',
    primarySelected: '#d8d8d8',
    secondarySelected: '#bababa',
    defaultBorder: '#bababa',
    primaryBorder: '#bababa',
    secondaryBorder: '#bababa',
    disabled: 'lightgray',
    shadow: 'black',
  },
};
